baseURL: http://mindthemath.com/
languageCode: en-us
title: Mind the Math
theme: PaperMod
copyright: "Mind the Math LLC"

enableInlineShortcodes: true
enableRobotsTXT: true
enableEmoji: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  env: dev # to enable google analytics, opengraph, twitter-cards and schema.
  title: MindtheMath
  description: ""
  keywords: [Consulting, Mathematics, Computation]
  # author: ["Michael Pilosov"]
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "2006-01-02"
  defaultTheme: auto # dark, light
  disableThemeToggle: false
  ShowReadingTime: false
  ShowShareButtons: true  # global override of disableShare
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: false
  ShareButtons: ["linkedin", "twitter", "reddit"]
  ShowRssButtonInSectionTermList: true
  UseHugoToc: false
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: true
  hideSummary: true
  searchHidden: false
  showtoc: false
  tocopen: false
  editPost:
      URL: "https://github.com/mindthemath/home/tree/main/content"
      Text: "Suggest Changes" # edit text
      appendFilePath: true # to append file path to Edit link
  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: ""
    favicon16x16: ""
    favicon32x32: ""
    apple_touch_icon: ""
    safari_pinned_tab: ""

  label:
    text: "MTM"
    # icon: /apple-touch-icon.png
    iconHeight: 35
  ######################################################
  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: "Mind the Math"
    subtitle: "Clarity for Computational Complexity"
    # imageUrl: "https://www.mpilosov.com/profile.webp"  # TODO image
    imageUrl: "https://files.clfx.cc/i/mtm-logo-sm.png"
    imageWidth: 150
    imageHeight: 150
    # imageTitle: profile-pic
    buttons:
      - name: About
        url: about
      - name: Services
        url: services
      - name: Workshops
        url: workshops
      # place for repo's writeup page
      - name: Resources # TODO: make this a blog
        url: blog
      - name: Contact
        url: contact

  ######################################################

  # home-info mode
  homeInfoParams:
    Title: "Mind the Math"
    Content: "Consulting for Clarity in Computational Complexity"

  ######################################################
  socialIcons:
    - name: github
      url: "https://github.com/mindthemath/"
    - name: linkedin
      url: "https://linkedin.com/in/mathematicalmichael"
    - name: email
      url: "mailto:solutions@mindthemath.com"
    # - name: github-alt
    #   url: "https://github.com/ml-starter-packs/"
    # - name: instagram
    #   url: "https://instagram.com/mind.the.math/"
  ######################################################
  
  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  # global editing option
  # editPost:
  #  URL: "https://github.com/<path_to_repo>/content"
  #  Text: "Suggest Changes" # edit text
  #  appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
  
######################################################
menu:
  main:
    - identifier: search
      name: ":mag:"
      url: /search/
      weight: 100
    - identifier: blog
      name: ":pen:"
      url: /blog/
      weight: 5
    # - identifier: about
    #   name: "about"
    #   url: /about/
    #   weight: 5
    # - identifier: workshops
    #   name: "workshops"
    #   url: /workshops/
    #   weight: 10
    # - identifier: tags
    #   name: "tags"
    #   url: /tags/
    #   weight: 20
    - identifier: contact
      name: ":email:"
      url: /contact/
      weight: 50
    # - identifier: blog
    #   name: "blog"
    #   url: /blog
    #   weight: 40
######################################################

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary

